### ISSUE TITLE
Support return the result as a pandas.DataFrame object

### ISSUE THREAD

**Issue by litaotao** [jaysw/ipydb#8]
Hi, I'm adding a feature on supporting return the sql result as a pandas.dataframe, I think this will make ipydb more powerful.

For now, ipydb is very useful for do ad-hoc both in console and ipython notebook, but people will take more actions on the result, which will almost use pandas, scipy, numpy, matplotlib in most cases, so I believe return a pandas.dataframe object will be much more useful and flexible.

what's more, it will be more clear if people just want to see the result for the display of dataframe is an excel table like style.

thanks, how do you guys think about this feature, I'm working on it now.

links:

- [pandas](http://pandas.pydata.org/)
- [pandas-dataframe-intro-step-1](http://nbviewer.ipython.org/github/litaotao/data-science/blob/master/examples/Pandas%20DataFrame%20%E8%AF%A6%E8%A7%A3%E4%B9%8B1%20%EF%BC%8D%20%E6%9E%84%E5%BB%BA%20%20DataFrame.ipynb)
- [pandas in data analyst and data science, example](http://nbviewer.ipython.org/github/litaotao/data-science/blob/master/examples/happy-healthy-hungry/h3.ipynb)

screenshots:

table style explore data

![pandas dataframe](http://i.stack.imgur.com/G5PWJ.png)

**Comment by jaysw** [comment]
Hello litaotao, 

Thanks for your interest in ipydb! 

Yes, I think this is a great idea. 
ipydb was initially designed to only work with the ipython-consoIe (running in a terminal). I have been wanting to add support for viewing queries in the popular web-based ipython-notebook for some time now. Indeed using pandas dataframes for output provides a quick path to running ipydb queries in a notebook. I will take a look at your PR soon. Thanks again!

Jay.

**Comment by jaysw** [comment]
Fixed in #10
